version: "3"

services:
  flask:
    build: ./server/
    container_name: flask-servers
    working_dir: /var/www/server
    ports:
        - 5000:5000
    volumes:
        - ./server/:/var/www/server
    command: python manage.py runserver --host=0.0.0.0
    env_file:
        - .env
    depends_on:
        - database
  database:
    image: postgres:10
    container_name: flask-databases
    volumes:
      - ./initial.sql:/docker-entrypoint-initdb.d/initial.sql
  node:
    image: node:10
    container_name: node-clients
    working_dir: /var/www/client/
    command: yarn start
    ports:
        - 3000:3000
    env_file:
      - .env
    volumes:
        - ./server/:/var/www/server/
        - ./client/:/var/www/client/
